import { NextResponse } from "next/server";
import { createArticle } from "@/services/article-service";

interface RankBetterRequest {
  gbpUrl: string;
  tenantSlug?: string;
}

interface RankBetterResponse {
  jobId: string;
  article: { id: string; slug: string };
}

const MOCK_MARKDOWN = `# 10 Ways to Boost Your Bakery's Local Search Rankings in 2026

If you're running a local bakery, your Google Business Profile is the single most important piece of digital real estate you own. When someone searches "bakery near me," it determines whether they walk into your shop or your competitor's.

## 1. Optimize Your Business Description

Your business description should include your primary keywords naturally. Instead of "We are a bakery," try "Sunrise Bakery is Austin's go-to artisan bakery specializing in sourdough bread, custom wedding cakes, and French pastries."

## 2. Post Weekly Updates

Google rewards active profiles. Businesses that post weekly see **2x more profile views** than those that don't.

> **Pro tip:** Schedule your posts for Tuesday or Wednesday mornings.

## 3. Respond to Every Review

Review engagement signals to Google that you're an active, responsive business. This alone can improve your local ranking position by several spots.

## 4. Add High-Quality Photos Regularly

Profiles with 100+ photos get **520% more calls** than the average business.

## 5. Use Google Posts for Offers

Create time-limited offers through Google Posts. Click-through rates increase by up to 35%.

## 6. Complete Every Profile Field

A 100% complete profile ranks significantly higher than a 60% complete one.

## 7. Build Local Citations

Ensure your NAP is consistent across Yelp, TripAdvisor, Apple Maps, and local directories.

## 8. Encourage Questions & Answers

Actively seed the Q&A section with common questions customers ask.

## 9. Track Your Competitors

Monitor what your top-ranking competitors are doing differently.

## 10. Create Location-Specific Content

Write blog content that targets your specific city and neighborhood.

---

*Generated by Lokal to help improve your local search visibility.*
`;

export async function POST(
  request: Request
): Promise<NextResponse<RankBetterResponse | { error: string }>> {
  let body: RankBetterRequest;
  try {
    body = (await request.json()) as RankBetterRequest;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { gbpUrl, tenantSlug = "tenant1" } = body;

  if (!gbpUrl || typeof gbpUrl !== "string") {
    return NextResponse.json(
      { error: "gbpUrl is required" },
      { status: 400 }
    );
  }

  try {
    const jobId = crypto.randomUUID();
    const article = await createArticle({
      jobId,
      markdownContent: MOCK_MARKDOWN,
      tenantSlug,
      title: "10 Ways to Boost Your Bakery's Local Search Rankings in 2026",
    });

    return NextResponse.json({
      jobId,
      article: { id: article.id, slug: article.slug },
    });
  } catch (err) {
    console.error("rank-better failed:", err);
    return NextResponse.json(
      { error: "Failed to generate article. Please try again." },
      { status: 500 }
    );
  }
}
