import { NextResponse } from "next/server";
import { createArticle } from "@/services/article-service";

interface RankBetterRequest {
  profileId: string;
  tenantSlug?: string;
}

interface RankBetterResponse {
  jobId: string;
  markdownContent: string;
  article: {
    id: string;
    slug: string;
    url: string;
  };
}

const MOCK_MARKDOWN = `# 10 Ways to Boost Your Bakery's Local Search Rankings in 2026

If you're running a local bakery, your Google Business Profile is the single most important piece of digital real estate you own. When someone searches "bakery near me," it determines whether they walk into your shop or your competitor's.

Here are ten proven strategies to climb the local rankings and attract more foot traffic.

## 1. Optimize Your Business Description

Your business description should include your primary keywords naturally. Instead of "We are a bakery," try "Sunrise Bakery is Austin's go-to artisan bakery specializing in sourdough bread, custom wedding cakes, and French pastries." Every word counts toward how Google understands your business.

## 2. Post Weekly Updates

Google rewards active profiles. Share new menu items, seasonal specials, behind-the-scenes photos of your baking process, or community events. Businesses that post weekly see **2x more profile views** than those that don't.

> **Pro tip:** Schedule your posts for Tuesday or Wednesday mornings — that's when most people plan their weekend bakery visits and search for local options.

## 3. Respond to Every Review

Review engagement signals to Google that you're an active, responsive business. Thank positive reviewers by name and address concerns in negative reviews professionally. This alone can improve your local ranking position by several spots.

## 4. Add High-Quality Photos Regularly

Profiles with 100+ photos get **520% more calls** than the average business. Upload professional photos of your products, interior, team, and seasonal displays. Aim for at least 5 new photos per month.

## 5. Use Google Posts for Offers

Create time-limited offers through Google Posts. "20% off custom cakes this weekend" creates urgency and increases click-through rates by up to 35%.

## 6. Complete Every Profile Field

Fill out every single field Google provides — services, menu items, accessibility features, payment methods, parking information. A 100% complete profile ranks significantly higher than a 60% complete one.

## 7. Build Local Citations

Ensure your business name, address, and phone number (NAP) are consistent across Yelp, TripAdvisor, Apple Maps, and local directories. Inconsistencies confuse Google and hurt your rankings.

## 8. Encourage Questions & Answers

Actively seed the Q&A section of your profile with common questions customers ask. "Do you make gluten-free options?" "Can I order a custom cake for Saturday?" Answer them thoroughly.

## 9. Track Your Competitors

Monitor what your top-ranking competitors are doing differently. If they post more frequently, have more reviews, or use better keywords, those are your areas for improvement.

## 10. Create Location-Specific Content

Write blog content that targets your specific city and neighborhood. "Best Sourdough Bread in South Austin" or "Wedding Cake Trends in Austin 2026" helps Google associate your business with local search intent.

---

*This article was generated by Lokal to help improve your local search visibility. For a detailed audit of your Google Business Profile, visit your dashboard.*
`;

export async function POST(request: Request): Promise<NextResponse<RankBetterResponse | { error: string }>> {
  let body: RankBetterRequest;
  try {
    body = (await request.json()) as RankBetterRequest;
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body" },
      { status: 400 }
    );
  }

  const { profileId, tenantSlug = "tenant1" } = body;

  if (!profileId || typeof profileId !== "string") {
    return NextResponse.json(
      { error: "profileId is required and must be a string" },
      { status: 400 }
    );
  }

  try {
    const jobId = crypto.randomUUID();
    const article = await createArticle({
      jobId,
      markdownContent: MOCK_MARKDOWN,
      profileId,
      tenantSlug,
      title: "10 Ways to Boost Your Bakery's Local Search Rankings in 2026",
    });

    return NextResponse.json({
      jobId,
      markdownContent: MOCK_MARKDOWN,
      article: {
        id: article.id,
        slug: article.slug,
        url: `/blog/${tenantSlug}/${article.slug}`,
      },
    });
  } catch (err) {
    console.error("rank-better failed:", err);
    return NextResponse.json(
      { error: "Failed to generate article. Please try again." },
      { status: 500 }
    );
  }
}
