import { config } from "dotenv";
config({ path: ".env.local" });
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import * as schema from "./schema";

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error("DATABASE_URL is not set");
    process.exit(1);
  }

  console.log("Seeding database...");

  const sql = neon(url);
  const db = drizzle({ client: sql, schema });

  const existingArticles = await db.select().from(schema.articles).limit(1);
  if (existingArticles.length > 0) {
    console.log("Database already seeded, skipping.");
    process.exit(0);
  }

  await db.insert(schema.articles).values({
    jobId: "seed-job-001",
    tenantSlug: "tenant1",
    slug: "10-ways-to-boost-your-bakerys-local-search-rankings-in-2026",
    title: "10 Ways to Boost Your Bakery's Local Search Rankings in 2026",
    markdownContent: SEED_MARKDOWN,
    status: "published",
    publishedAt: new Date(),
  });

  console.log("Seed complete: 1 article inserted.");
  process.exit(0);
}

const SEED_MARKDOWN = `# 10 Ways to Boost Your Bakery's Local Search Rankings in 2026

If you're running a local bakery, your Google Business Profile is the single most important piece of digital real estate you own.

## 1. Optimize Your Business Description

Your business description should include your primary keywords naturally. Instead of "We are a bakery," try "Sunrise Bakery is Austin's go-to artisan bakery specializing in sourdough bread, custom wedding cakes, and French pastries."

## 2. Post Weekly Updates

Google rewards active profiles. Businesses that post weekly see **2x more profile views** than those that don't.

## 3. Respond to Every Review

Review engagement signals to Google that you're an active, responsive business. This alone can improve your local ranking position by several spots.

## 4. Add High-Quality Photos Regularly

Profiles with 100+ photos get **520% more calls** than the average business.

## 5. Use Google Posts for Offers

Create time-limited offers through Google Posts to increase click-through rates by up to 35%.

## 6. Complete Every Profile Field

A 100% complete profile ranks significantly higher than a 60% complete one.

## 7. Build Local Citations

Ensure your NAP is consistent across Yelp, TripAdvisor, Apple Maps, and local directories.

## 8. Encourage Questions & Answers

Actively seed the Q&A section with common questions customers ask.

## 9. Track Your Competitors

Monitor what your top-ranking competitors are doing differently.

## 10. Create Location-Specific Content

Write blog content that targets your specific city and neighborhood.

---

*Generated by Lokal to help improve your local search visibility.*
`;

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
